### ISSUE TITLE
Move to JuliaTesting?

### ISSUE THREAD

**Issue by oxinabox** [JuliaTesting/MetaTesting.jl#4]
I would like to propose we move this to JuliaTesting.
I am happy to add @sethaxen and @nickrobinson251  to that org.

For me to do the move that I would need to be granted admin of this repo.

**Comment by sethaxen** [comment]
Yes that would be great! I've added you as a collaborator to the repo but there doesn't seem to be an admin option. Is this sufficient, or do I need to transfer ownership to you first?

**Comment by oxinabox** [comment]
Ah maybe there is only an admin option if already in an org. 
Yes. I think you would need to transfer ownership to me then

I have invited you both to the org.  Yous can go to  https://github.com/JuliaTesting  to accept
